services:

  postgres:
    image: postgres:14.2-alpine
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python3 -m src.main
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
