commands:
  - command: "start"
    description: "Запускает бота и states"
    response: "bot && states"
  - command: "help"
    description: "Показывает доступные команды"
    response: "Доступные команды: /start, /help"
  - command: "cancel"
    description: "exit from states of registration"
    response: "cancel states to zero, exit from states"
  - command: "lang"
    description: "change language for user"
    response: "change language for user"
  - command: "show_rules"
    description: "show rules agreement"
    response: "show rules"
#